### ISSUE TITLE
Images fail to load through GBIF image cache

### ISSUE THREAD

**Issue by timrobertson100** [gbif/hp-bison#5]
On https://hp-bison.gbif-staging.org/ some images fail to load when put through the image cache. 

For example, this image exists
  https://hp-bison.gbif-staging.org/assets/images/https___deepseacoraldata.noaa.gov_db-images_918242.jpg

But returns 504 when run through Thumbor
  https://api.gbif.org/v1/image/unsafe/600x300/https%3A%2F%2Fhp-bison.gbif-staging.org%2Fassets%2Fimages%2Fhttps___deepseacoraldata.noaa.gov_db-images_918242.jpg

**Comment by timrobertson100** [comment]
This is not a filename issue, but looking at the JPEGs they are using JFIF encoding. Perhaps this is the cause

**Comment by timrobertson100** [comment]
I've tried rewriting the file - still no success.
Taking the original file (renamed) and copying it to a new URL works though.

Works:
https://api.gbif.org/v1/image/unsafe/600x300/https://download.gbif.org/tim/orig.jpg

Does not work (same file):
https://api.gbif.org/v1/image/unsafe/600x300/https://hp-bison.gbif-staging.org/assets/images/deepseacoraldata.jpg

**Comment by MattBlissett** [comment]
One of the two Thumbor servers hadn't had the new certificates installed automatically, and Letsencrypt now needs the updated one: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

It should be working now.
