### ISSUE TITLE
consider rotating the image

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-bison#6]
I'm aware that you have plenty to do, so feel free to just close this. But perhaps a rotated image would work better with the cropping here https://www.gbif.us/post/2021/usgs-bbl-statecentroid/
https://github.com/gbif/hp-bison/blob/9b8f909f101cde0801e7ac483301e5be0aa14bca/_posts/2021-10-06-USGS_BBL_StateCentroid.md?plain=1#L5

I've uploaded a rotated version https://github.com/gbif/hp-bison/commit/9b8f909f101cde0801e7ac483301e5be0aa14bca

**Comment by AbbyBenson** [comment]
Yes that looks much better. Thanks Morten!
